name: frontend
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  go_router: ^5.1.5
  http: ^0.13.5
  layout: ^1.0.3
  requests: ^4.8.0-alpha.0

dev_dependencies:
  ficcanaso: ^4.0.0
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
    - .env