name: HikeTracker
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  equatable: ^2.0.5
  file_picker: ^5.2.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_map: ^3.0.0
  go_router: ^5.1.5
  gpx: ^2.2.0
  http: ^0.13.5
  latlong2: ^0.8.1
  layout: ^1.0.3
  requests: ^4.8.0-alpha.0

dev_dependencies:
  ficcanaso: ^4.0.0
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
    - .env
    - assets/images/