### getHikeByDifficulty
GET http://localhost:3001/api/hike/T/

### getHikeByAscent
GET http://localhost:3001/api/hike/1000/

### getHikeByLength
GET http://localhost:3001/api/hike/10/

### getHikeByTime
GET http://localhost:3001/api/hike/5/

### getHikeByArea
GET http://localhost:3001/api/hike/Talucco/