# syntax=docker/dockerfile:1

FROM node:16.14.0
ENV NODE_ENV=production

WORKDIR /app

COPY ["package.json", "package-lock.json*", "./"]

RUN npm install --production

COPY . .

EXPOSE 3001

CMD [ "node", "index.js" ]